# Generated by Django 6.1 on 2026-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
