# Generated by Django 6.1 on 2026-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentleave_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='deleted_time',
            field=models.DateTimeField(null=True),
        ),
    ]
